//
//  MoviesTimeStyleKit.m
//  MoviesTime
//
//  Created by Diego Bartra on 11/6/16.
//  Copyright (c) 2016 ArcTouch. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import "MoviesTimeStyleKit.h"


@implementation MoviesTimeStyleKit

#pragma mark Cache

static UIColor* _themeColor = nil;
static UIColor* _highlightThemeColor = nil;
static UIColor* _placeholderColor = nil;
static UIColor* _selectionColor = nil;

#pragma mark Initialization

+ (void)initialize
{
    // Colors Initialization
    _themeColor = [UIColor colorWithRed: 0.422 green: 0 blue: 0.867 alpha: 1];
    CGFloat themeColorRGBA[4];
    [_themeColor getRed: &themeColorRGBA[0] green: &themeColorRGBA[1] blue: &themeColorRGBA[2] alpha: &themeColorRGBA[3]];

    _highlightThemeColor = [UIColor colorWithRed: (themeColorRGBA[0] * 0.6 + 0.4) green: (themeColorRGBA[1] * 0.6 + 0.4) blue: (themeColorRGBA[2] * 0.6 + 0.4) alpha: (themeColorRGBA[3] * 0.6 + 0.4)];
    _placeholderColor = [UIColor colorWithRed: 0.694 green: 0.694 blue: 0.694 alpha: 1];
    _selectionColor = [UIColor colorWithRed: 0.009 green: 0.643 blue: 1 alpha: 1];

}

#pragma mark Colors

+ (UIColor*)themeColor { return _themeColor; }
+ (UIColor*)highlightThemeColor { return _highlightThemeColor; }
+ (UIColor*)placeholderColor { return _placeholderColor; }
+ (UIColor*)selectionColor { return _selectionColor; }

#pragma mark Drawing Methods

+ (void)drawHighlightedBorderedButtonWithFrame: (CGRect)frame
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 1, CGRectGetWidth(frame) - 2.5, CGRectGetHeight(frame) - 2) cornerRadius: 3];
    [MoviesTimeStyleKit.themeColor setFill];
    [rectanglePath fill];
    [MoviesTimeStyleKit.themeColor setStroke];
    rectanglePath.lineWidth = 1;
    [rectanglePath stroke];
}

+ (void)drawBorderedButtonWithFrame: (CGRect)frame
{

    //// Rectangle Drawing
    UIBezierPath* rectanglePath = [UIBezierPath bezierPathWithRoundedRect: CGRectMake(CGRectGetMinX(frame) + 1, CGRectGetMinY(frame) + 1, CGRectGetWidth(frame) - 2.5, CGRectGetHeight(frame) - 2) cornerRadius: 3];
    [MoviesTimeStyleKit.themeColor setStroke];
    rectanglePath.lineWidth = 2;
    [rectanglePath stroke];
}

#pragma mark Generated Images

+ (UIImage*)imageOfHighlightedBorderedButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [MoviesTimeStyleKit drawHighlightedBorderedButtonWithFrame: CGRectMake(0, 0, frame.size.width, frame.size.height)];

    UIImage* imageOfHighlightedBorderedButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfHighlightedBorderedButton;
}

+ (UIImage*)imageOfBorderedButtonWithFrame: (CGRect)frame
{
    UIGraphicsBeginImageContextWithOptions(frame.size, NO, 0.0f);
    [MoviesTimeStyleKit drawBorderedButtonWithFrame: CGRectMake(0, 0, frame.size.width, frame.size.height)];

    UIImage* imageOfBorderedButton = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();

    return imageOfBorderedButton;
}

@end
