//
//  MoviesTimeStyleKit.h
//  MoviesTime
//
//  Created by Diego Bartra on 11/6/16.
//  Copyright (c) 2016 ArcTouch. All rights reserved.
//
//  Generated by PaintCode (www.paintcodeapp.com)
//

#import <Foundation/Foundation.h>
#import <UIKit/UIKit.h>


@interface MoviesTimeStyleKit : NSObject

// Colors
+ (UIColor*)themeColor;
+ (UIColor*)highlightThemeColor;
+ (UIColor*)placeholderColor;
+ (UIColor*)selectionColor;

// Generated Images
+ (UIImage*)imageOfHighlightedBorderedButtonWithFrame: (CGRect)frame;
+ (UIImage*)imageOfBorderedButtonWithFrame: (CGRect)frame;

@end
